# Generated by Django 3.0.4 on 2020-03-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('std_number', models.IntegerField()),
                ('teacher', models.CharField(choices=[('razavizadeh', 'Razavizadeh'), ('vakili', 'Vakili'), ('beheshti', 'Beheshti')], max_length=12)),
            ],
        ),
    ]
